NDefines.NDiplomacy.JAIN_LIEGE_OPINION_BONUS = 5

NDefines.NDiplomacy.MAKE_CONSORT_INTERACTION_ENABLED = 0
NDefines.NDiplomacy.DISMISS_CONSORT_INTERACTION_ENABLED = 0
NDefines.NDiplomacy.OFFER_CONSORT_INTERACTION_ENABLED = 0
NDefines.NDiplomacy.ASK_TO_EMBARGO_INTERACTION_ENABLED = 0

NDefines.NEngine.EVENT_PROCESS_OFFSET = 30 		
NDefines.NEngine.COURTIER_EVENT_PROCESS_OFFSET = 75

NDefines.NCharacter.FEMALE_ATTRACTION_CUTOFF = 65