NDefines.NDiplomacy.JAIN_LIEGE_OPINION_BONUS = 5

NDefines.NDiplomacy.MAKE_CONSORT_INTERACTION_ENABLED = 0
NDefines.NDiplomacy.DISMISS_CONSORT_INTERACTION_ENABLED = 0
NDefines.NDiplomacy.OFFER_CONSORT_INTERACTION_ENABLED = 0
NDefines.NDiplomacy.ASK_TO_EMBARGO_INTERACTION_ENABLED = 0
NDefines.NDiplomacy.DOWRY_MULTIPLIER = 2.0

NDefines.NEngine.EVENT_PROCESS_OFFSET = 30 		
NDefines.NEngine.COURTIER_EVENT_PROCESS_OFFSET = 75

NDefines.NCharacter.FEMALE_ATTRACTION_CUTOFF = 65
NDefines.NCharacter.COURT_SIZE_CHILD_PENALTY_THRESHOLD = 9999

NDefines.NTitle.BARON_LANDLESS_SON_PRESTIGE = 0
NDefines.NTitle.COUNT_LANDLESS_SON_PRESTIGE = 0
NDefines.NTitle.DUKE_LANDLESS_SON_PRESTIGE = 0
NDefines.NTitle.KING_LANDLESS_SON_PRESTIGE = 0
NDefines.NTitle.EMPEROR_LANDLESS_SON_PRESTIGE = 0

NDefines.NEconomy.PATRICIAN_FAMILY_SHARES_REST = 0